# -*- coding: utf-8 -*-
"""Copy of text_generation

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ikyo0etW5MbpWemGp0LvKWrJYTzNlj_2
"""

!pip install transformers

from transformers import GPT2LMHeadModel, GPT2Tokenizer

tokenizer = GPT2Tokenizer.from_pretrained("gpt2")
model = GPT2LMHeadModel.from_pretrained("gpt2")

text = "What is Natural Language Processing?"

encoded_input = tokenizer.encode(text, return_tensors='pt')

output = model.generate(encoded_input, max_length=500, num_beams=5,no_repeat_ngram_size=2, early_stopping=True)

tokenizer.decode(output[0], skip_special_tokens=True)